[package]
name = "sjconv"
version = "0.1.0"
edition = "2024"

[profile.release]
codegen-units = 1
lto = "fat"

[dependencies]
jack = "0.13.2"
fft-convolver = "0.2.0"
hound = "3.5.1"
clap = { version = "4.5.34", features = ["derive"] }
